[2023-01-29T16:35:27.651+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crawl_data.save-to-hdfs scheduled__2023-01-29T15:05:00+00:00 [queued]>
[2023-01-29T16:35:27.666+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crawl_data.save-to-hdfs scheduled__2023-01-29T15:05:00+00:00 [queued]>
[2023-01-29T16:35:27.666+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T16:35:27.666+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-01-29T16:35:27.666+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T16:35:27.689+0000] {taskinstance.py:1300} INFO - Executing <Task(SSHOperator): save-to-hdfs> on 2023-01-29 15:05:00+00:00
[2023-01-29T16:35:27.694+0000] {standard_task_runner.py:55} INFO - Started process 16708 to run task
[2023-01-29T16:35:27.697+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crawl_data', 'save-to-hdfs', 'scheduled__2023-01-29T15:05:00+00:00', '--job-id', '1501', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data.py', '--cfg-path', '/tmp/tmpw8txcwld']
[2023-01-29T16:35:27.698+0000] {standard_task_runner.py:83} INFO - Job 1501: Subtask save-to-hdfs
[2023-01-29T16:35:27.779+0000] {task_command.py:388} INFO - Running <TaskInstance: crawl_data.save-to-hdfs scheduled__2023-01-29T15:05:00+00:00 [running]> on host 9be4ecca8506
[2023-01-29T16:35:27.871+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=phukaioh
AIRFLOW_CTX_DAG_ID=crawl_data
AIRFLOW_CTX_TASK_ID=save-to-hdfs
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T15:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-29T15:05:00+00:00
[2023-01-29T16:35:27.871+0000] {ssh.py:133} INFO - Creating ssh_client
[2023-01-29T16:35:27.872+0000] {ssh.py:283} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-01-29T16:35:27.885+0000] {transport.py:1874} INFO - Connected (version 2.0, client OpenSSH_8.2p1)
[2023-01-29T16:35:27.963+0000] {transport.py:1874} INFO - Authentication (password) successful!
[2023-01-29T16:35:27.964+0000] {ssh.py:460} INFO - Running command: /opt/hadoop/bin/hdfs dfs -copyFromLocal -f /home/phukaioh/Documents/intro-data-science/crawler/data/vietnamnet.json /data/vietnamnet/vietnamnet-29-01-2023.json 
[2023-01-29T16:35:32.678+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=crawl_data, task_id=save-to-hdfs, execution_date=20230129T150500, start_date=20230129T163527, end_date=20230129T163532
[2023-01-29T16:35:32.771+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-29T16:35:32.799+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
